### ISSUE TITLE
Tomcat warning log at startup

### ISSUE THREAD

**Issue by sevketarisu** [CS576-SEVKET-CEREN-GOKHAN-OMERCAN/LiveVideoStreamProject#2]
Tomcat produces a warning message at startup but the server starts successfully

WARNING: JSF1064: Unable to find or serve resource, messages/messages.png, from
library, primefaces.
Eki 26, 2015 1:00:50 PM com.sun.faces.application.resource.ResourceHandlerImpl l
ogMissingResource
WARNING:
org.apache.catalina.connector.ClientAbortException: java.io.IOException
        at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffe
r.java:407)
        at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:480)
        at org.apache.tomcat.util.buf.ByteChunk.append(ByteChunk.java:366)
        at org.apache.catalina.connector.OutputBuffer.writeBytes(OutputBuffer.ja
va:432)
        at org.apache.catalina.connector.OutputBuffer.write(OutputBuffer.java:42
0)
        at org.apache.catalina.connector.CoyoteOutputStream.write(CoyoteOutputSt
ream.java:91)
        at java.nio.channels.Channels$WritableByteChannelImpl.write(Channels.jav
a:458)
        at com.sun.faces.application.resource.ResourceHandlerImpl.handleResource
Request(ResourceHandlerImpl.java:283)
        at javax.faces.application.ResourceHandlerWrapper.handleResourceRequest(
ResourceHandlerWrapper.java:125)
        at org.primefaces.application.PrimeResourceHandler.handleResourceRequest
(PrimeResourceHandler.java:132)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:591)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52
)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperV
alve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextV
alve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(Authentica
torBase.java:505)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.j
ava:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.j
ava:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:
956)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineVal
ve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.jav
a:423)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp
11Processor.java:1079)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(
AbstractProtocol.java:625)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpo
int.java:2522)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoin
t.java:2511)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskTh
read.java:61)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.IOException
        at org.apache.coyote.http11.InternalAprOutputBuffer.flushBuffer(Internal
AprOutputBuffer.java:205)
        at org.apache.coyote.http11.InternalAprOutputBuffer.access$100(InternalA
prOutputBuffer.java:37)
        at org.apache.coyote.http11.InternalAprOutputBuffer$SocketOutputBuffer.d
oWrite(InternalAprOutputBuffer.java:235)
        at org.apache.coyote.http11.filters.ChunkedOutputFilter.doWrite(ChunkedO
utputFilter.java:119)
        at org.apache.coyote.http11.AbstractOutputBuffer.doWrite(AbstractOutputB
uffer.java:192)
        at org.apache.coyote.Response.doWrite(Response.java:499)
        at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffe
r.java:402)
        ... 31 more

**Comment by gokhandinc** [comment]
fixed

**Comment by sevketarisu** [comment]
tested
